version: '3.7'

services:
  onebox:
    container_name: onebox-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  default:
    name: app_onebox-network
    external: true