version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      target: ${TARGET:-development}
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    networks:
      crypitor-network:
        aliases:
          - api
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
  monitor:
    container_name: monitor
    build:
      context: .
      target: ${TARGET:-development}
      dockerfile: ./apps/monitor-service/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      crypitor-network:
        aliases:
          - monitor
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
  worker:
    container_name: worker
    build:
      context: .
      target: ${TARGET:-development}
      dockerfile: ./apps/worker-service/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      crypitor-network:
        aliases:
          - worker
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
  redis:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: redis
    networks:
      crypitor-network:
        aliases:
          - redis
  mongo:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: mongo
    networks:
      crypitor-network:
        aliases:
          - mongo

  zookeeper:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: zookeeper
    networks:
      crypitor-network:
        aliases:
          - zookeeper

  kafka:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - kafka
  kafka-ui:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - kafka-ui
  postgres:
    extends:
      file: ./docker/docker-compose-wh.yml
      service: postgres
    networks:
      crypitor-network:
        aliases:
          - postgres

  webhook-migrate:
    extends:
      file: ./docker/docker-compose-wh.yml
      service: webhook-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - webhook-migrate

  webhook-worker:
    extends:
      file: ./docker/docker-compose-wh.yml
      service: webhook-worker
    depends_on:
      postgres:
        condition: service_healthy
      webhook-migrate:
        condition: service_completed_successfully
    networks:
      crypitor-network:
        aliases:
          - webhook-worker

  webhook-server:
    extends:
      file: ./docker/docker-compose-wh.yml
      service: webhook-server
    depends_on:
      postgres:
        condition: service_healthy
      webhook-migrate:
        condition: service_completed_successfully
    networks:
      crypitor-network:
        aliases:
          - webhook-server
networks:
  crypitor-network:
volumes:
  pgdata:
  data:
