version: '3.7'

services:
  crypitor-backend:
    container_name: crypitor-backend
    build:
      context: .
      target: ${TARGET:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
      - 9229:9229
    env_file:
      - .env
      - ./src/apps/main/.env
    environment:
      - MAIN_FILE=apps/main/main
      - SERVER_PORT=3002
    networks:
      crypitor-network:
        aliases:
        - crypitor-backend
    depends_on:
      - redis
      - mongo
  crypitor-scanner:
    container_name: crypitor-scanner
    build:
      context: .
      target: ${TARGET:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003
      - 9229:9229
    env_file:
      - .env
      - ./src/apps/scanner/.env
    environment:
      - MAIN_FILE=apps/scanner/main
      - SERVER_PORT=3003
    networks:
      crypitor-network:
        aliases:
        - crypitor-scanner
    depends_on:
      - redis
      - mongo
  crypitor-webhook:
    container_name: crypitor-webhook
    build:
      context: .
      target: ${TARGET:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3004
      - 9229:9229
    env_file:
      - .env
      - ./src/apps/webhook/.env
    environment:
      - MAIN_FILE=apps/webhook/main
      - SERVER_PORT=3004
    networks:
      crypitor-network:
        aliases:
        - crypitor-webhook
    depends_on:
      - redis
      - mongo
  redis:
    container_name: redis
    image: redis:5
    networks:
      crypitor-network:
        aliases:
        - redis
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db
      - ./.config/mongo-entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    networks:
      crypitor-network:
        aliases:
        - mongo
networks:
  crypitor-network:
volumes:
  pgdata:
  data: