version: '3.7'

services:
  onebox:
    container_name: onebox
    build:
      context: ..
      target: ${TARGET:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      crypitor-network:
        aliases:
        - onebox
    depends_on:
      - redis
      - mongo
  monitor:
    container_name: monitor
    build:
      context: ..
      target: ${TARGET:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - APP=monitor-service
      
    networks:
      crypitor-network:
        aliases:
        - monitor
    depends_on:
      - redis
      - mongo
  worker:
    container_name: worker
    build:
      context: ..
      target: ${TARGET:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ../.env
    networks:
      crypitor-network:
        aliases:
        - worker
    depends_on:
      - redis
      - mongo
  redis:
    extends:
      file: ./docker-compose-deps.yml
      service: redis
    networks:
      crypitor-network:
        aliases:
        - redis
  mongo:
    extends:
      file: ./docker-compose-deps.yml
      service: mongo
    networks:
      crypitor-network:
        aliases:
        - mongo

  zookeeper:
    extends:
      file: ./docker-compose-deps.yml
      service: zookeeper
    networks:
      crypitor-network:
        aliases:
        - zookeeper

  kafka:
    extends:
      file: ./docker-compose-deps.yml
      service: kafka
    networks:
      crypitor-network:
        aliases:
        - kafka
networks:
  crypitor-network:
volumes:
  pgdata:
  data: