version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 80:80
      - 443:443
    environment:
      API_DOMAIN: ${API_DOMAIN:-localhost}
      SERVER_PORT: ${SERVER_PORT:-3000}
    volumes:
      - ../.config/nginx/:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - crypitor-network
  onebox:
    container_name: crypitor-onebox
    image: registry.gitlab.com/cauta/onebox:${VERSION:-master}
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    networks:
      crypitor-network:
        aliases:
          - onebox
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  monitor:
    container_name: crypitor-monitor
    image: registry.gitlab.com/cauta/crypitor-monitor:${VERSION:-master}
    env_file:
      - .env
    networks:
      crypitor-network:
        aliases:
          - monitor
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  worker:
    container_name: crypitor-worker
    image: registry.gitlab.com/cauta/crypitor-worker:${VERSION:-master}
    env_file:
      - .env
    networks:
      crypitor-network:
        aliases:
          - worker
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  redis:
    extends:
      file: docker-compose-deps.yml
      service: redis
    networks:
      crypitor-network:
        aliases:
          - redis
  mongo:
    extends:
      file: docker-compose-deps.yml
      service: mongo
    restart: always
    networks:
      crypitor-network:
        aliases:
          - mongo

  zookeeper:
    extends:
      file: docker-compose-deps.yml
      service: zookeeper
    restart: always
    networks:
      crypitor-network:
        aliases:
          - zookeeper

  kafka:
    extends:
      file: docker-compose-deps.yml
      service: kafka
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - kafka

  kafka-ui:
    extends:
      file: docker-compose-deps.yml
      service: kafka-ui
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - kafka-ui

  postgres:
    extends:
      file: docker-compose-wh.yml
      service: postgres
    networks:
      crypitor-network:
        aliases:
          - postgres

  webhook-migrate:
    extends:
      file: docker-compose-wh.yml
      service: webhook-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - webhook-migrate

  webhook-worker:
    extends:
      file: docker-compose-wh.yml
      service: webhook-worker
    depends_on:
      postgres:
        condition: service_healthy
      webhook-migrate:
        condition: service_completed_successfully
    networks:
      crypitor-network:
        aliases:
          - webhook-worker

  webhook-server:
    extends:
      file: docker-compose-wh.yml
      service: webhook-server
    depends_on:
      postgres:
        condition: service_healthy
      webhook-migrate:
        condition: service_completed_successfully
    networks:
      crypitor-network:
        aliases:
          - webhook-server

networks:
  crypitor-network:
volumes:
  pgdata:
  data:
