version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 80:80
      - 443:443
    environment:
      API_DOMAIN: ${API_DOMAIN:-localhost}
      SERVER_PORT: ${SERVER_PORT:-3000}
    volumes:
      - ../.config/nginx/:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - crypitor-network
    depends_on:
      - onebox
  onebox:
    container_name: crypitor-onebox
    image: crypitor/onebox:${VERSION:-master}
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    networks:
      crypitor-network:
        aliases:
          - onebox
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  monitor:
    container_name: crypitor-monitor
    image: crypitor/monitor:${VERSION:-master}
    env_file:
      - .env
    networks:
      crypitor-network:
        aliases:
          - monitor
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  worker:
    container_name: crypitor-worker
    image: crypitor/worker:${VERSION:-master}
    env_file:
      - .env
    networks:
      crypitor-network:
        aliases:
          - worker
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  redis:
    extends:
      file: docker-compose-deps.yml
      service: redis
    networks:
      crypitor-network:
        aliases:
          - redis
  mongo:
    extends:
      file: docker-compose-deps.yml
      service: mongo
    restart: always
    networks:
      crypitor-network:
        aliases:
          - mongo

  zookeeper:
    extends:
      file: docker-compose-deps.yml
      service: zookeeper
    restart: always
    networks:
      crypitor-network:
        aliases:
          - zookeeper

  kafka:
    extends:
      file: docker-compose-deps.yml
      service: kafka
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - kafka

  kafka-ui:
    extends:
      file: docker-compose-deps.yml
      service: kafka-ui
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      crypitor-network:
        aliases:
          - kafka-ui
networks:
  crypitor-network:
volumes:
  pgdata:
  data:
