version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 80:80
      - 443:443
    environment:
      API_DOMAIN: ${API_DOMAIN:-localhost}
    volumes:
      - ../.config/nginx/:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - crypitor-network
    depends_on:
      - onebox
  onebox:
    container_name: onebox
    image: crypitor/onebox
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      crypitor-network:
        aliases:
          - onebox
    depends_on:
      - redis
      - mongo
      - kafka
  monitor:
    container_name: monitor
    image: crypitor/monitor
    env_file:
      - .env.production
    networks:
      crypitor-network:
        aliases:
          - monitor
    depends_on:
      - redis
      - mongo
      - kafka
  worker:
    container_name: worker
    image: crypitor/worker
    env_file:
      - .env.production
    networks:
      crypitor-network:
        aliases:
          - worker
    depends_on:
      - redis
      - mongo
      - kafka
  redis:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: redis
    networks:
      crypitor-network:
        aliases:
          - redis
  mongo:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: mongo
    networks:
      crypitor-network:
        aliases:
          - mongo

  zookeeper:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: zookeeper
    networks:
      crypitor-network:
        aliases:
          - zookeeper

  kafka:
    extends:
      file: ./docker/docker-compose-deps.yml
      service: kafka
    networks:
      crypitor-network:
        aliases:
          - kafka
networks:
  crypitor-network:
volumes:
  pgdata:
  data:
