name: On Push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build app
      run: |
        cd app
        yarn && yarn build

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.gitlab.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Onebox Docker image
      run: |
        cd app
        docker build -f apps/onebox/Dockerfile --target production -t registry.gitlab.com/cauta/onebox:master .
        docker push registry.gitlab.com/cauta/onebox:master

    - name: Build and push Monitor Docker image
      run: |
        cd app
        docker build -f apps/monitor-service/Dockerfile --target production -t registry.gitlab.com/cauta/crypitor-monitor:master .
        docker push registry.gitlab.com/cauta/crypitor-monitor:master

    - name: Build and push Worker Docker image
      run: |
        cd app
        docker build -f apps/worker-service/Dockerfile --target production -t registry.gitlab.com/cauta/crypitor-worker:master .
        docker push registry.gitlab.com/cauta/crypitor-worker:master
